; SPDX-License-Identifier: Apache-2.0
;
; Compile-only harness for nsis-add-to-path.nsh / nsis-remove-from-path.nsh.
;
; Those two files are !include'd into a script generated by CPack's NSIS
; template, so nothing in a normal build or test run ever compiles them - a typo
; would first surface in `cpack -G NSIS` during a release. This harness declares
; the same context the template provides (the two PATH variables, WinMessages,
; an install and an uninstall section) and nothing else, so makensis type-checks
; both snippets on every push. See the windows-installer-scripts job in
; .github/workflows/ci.yml.
;
; NETVIS_PKG_DIR is passed on the command line as an ABSOLUTE, BACKSLASHED path,
; which is the form CMake substitutes into CPACK_NSIS_EXTRA_INSTALL_COMMANDS -- so
; compiling it that way here is what proves makensis accepts it. It does NOT accept
; a forward-slashed absolute path: !include reports "could not find" for a file that
; plainly exists, which is how the CMake side was caught before it reached a release.
; The fallback keeps a bare `makensis packaging\windows\nsh-syntax-check.nsi` working
; from a checkout: !include resolves a relative path against the INCLUDING SCRIPT's
; directory, not the working directory.
;
; From the repository root:
;   makensis /DNETVIS_PKG_DIR="<abs>\packaging\windows" packaging\windows\nsh-syntax-check.nsi

Name "netvis-nsh-syntax-check"
OutFile "nsh-syntax-check-installer.exe"
InstallDir "$PROGRAMFILES64\NetVis"
RequestExecutionLevel admin

!include "WinMessages.NSH"

!ifndef NETVIS_PKG_DIR
  !define NETVIS_PKG_DIR "."
!endif

; Declared by the CPack NSIS template; the snippets read both.
Var DO_NOT_ADD_TO_PATH
Var ADD_TO_PATH_ALL_USERS

Section "Install"
  WriteUninstaller "$INSTDIR\uninst.exe"
  !include "${NETVIS_PKG_DIR}\nsis-add-to-path.nsh"
SectionEnd

Section "Uninstall"
  !include "${NETVIS_PKG_DIR}\nsis-remove-from-path.nsh"
SectionEnd
