; SPDX-License-Identifier: Apache-2.0
;
; Compile-only harness for nsis-add-to-path.nsh / nsis-remove-from-path.nsh.
;
; Those two files are !include'd into a script generated by CPack's NSIS
; template, so nothing in a normal build or test run ever compiles them - a typo
; would first surface in `cpack -G NSIS` during a release. This harness declares
; the same context the template provides (the two PATH variables, WinMessages,
; an install and an uninstall section) and nothing else, so makensis type-checks
; both snippets on every push. See the windows-installer-scripts job in
; .github/workflows/ci.yml.
;
; Run from the repository root:  makensis packaging\windows\nsh-syntax-check.nsi

Name "netvis-nsh-syntax-check"
OutFile "nsh-syntax-check-installer.exe"
InstallDir "$PROGRAMFILES64\NetVis"
RequestExecutionLevel admin

!include "WinMessages.NSH"

; Declared by the CPack NSIS template; the snippets read both.
Var DO_NOT_ADD_TO_PATH
Var ADD_TO_PATH_ALL_USERS

Section "Install"
  WriteUninstaller "$INSTDIR\uninst.exe"
  !include "packaging\windows\nsis-add-to-path.nsh"
SectionEnd

Section "Uninstall"
  !include "packaging\windows\nsis-remove-from-path.nsh"
SectionEnd
