; SPDX-License-Identifier: Apache-2.0
;
; Compile-only harness for nsis-add-to-path.nsh / nsis-remove-from-path.nsh.
;
; Those two files are !include'd into a script generated by CPack's NSIS
; template, so nothing in a normal build or test run ever compiles them - a typo
; would first surface in `cpack -G NSIS` during a release. This harness stands in
; for the template: it declares the two PATH variables, provides WinMessages, the
; template's ConditionalAddToRegistry helper, and an install and an uninstall
; section, and nothing else, so makensis type-checks both snippets on every push.
; See the windows-installer-scripts job in .github/workflows/ci.yml.
;
; The harness has to reproduce how the real template SETS the two variables, not
; just that it declares them. makensis only counts a variable as referenced when
; it is written to (an output operand of StrCpy, ReadRegStr, ReadINIStr, ...);
; reading it inside a string or a StrCmp does not count, so a variable that is
; only ever read draws `warning 6001: not referenced or never set`, which /WX in
; the CI job turns into a failure. The real template does assign them:
;
;   Install section    -  from the options page INI (Field 2 and Field 3).
;                         nsis-add-to-path.nsh does this itself, so the harness
;                         does NOT pre-assign them there: the snippet has to stand
;                         on its own, because the template's copy is skipped when
;                         the user ticks "Do not create shortcuts".
;   Uninstall section  -  ReadRegStr from the uninstall registry key, just before
;                         EXTRA_UNINSTALL_COMMANDS, reproduced below.
;
; Do NOT silence 6001 with `!pragma warning disable`: it would also hide a
; variable that a later snippet genuinely forgot to set.
;
; NETVIS_PKG_DIR is passed on the command line as an ABSOLUTE, BACKSLASHED path,
; which is the form CMake substitutes into CPACK_NSIS_EXTRA_INSTALL_COMMANDS -- so
; compiling it that way here is what proves makensis accepts it. It does NOT accept
; a forward-slashed absolute path: !include reports "could not find" for a file that
; plainly exists, which is how the CMake side was caught before it reached a release.
; The fallback keeps a bare `makensis packaging\windows\nsh-syntax-check.nsi` working
; from a checkout: !include resolves a relative path against the INCLUDING SCRIPT's
; directory, not the working directory.
;
; From the repository root:
;   makensis /WX /DNETVIS_PKG_DIR="<abs>\packaging\windows" packaging\windows\nsh-syntax-check.nsi
;
; makensis writes OutFile next to this script unless /NOCD is given, which is why
; nsh-syntax-check-installer.exe is in .gitignore.

Name "netvis-nsh-syntax-check"
OutFile "nsh-syntax-check-installer.exe"
InstallDir "$PROGRAMFILES64\NetVis"
RequestExecutionLevel admin

!include "WinMessages.NSH"

!ifndef NETVIS_PKG_DIR
  !define NETVIS_PKG_DIR "."
!endif

; Declared by the CPack NSIS template; see above for who assigns them.
Var DO_NOT_ADD_TO_PATH
Var ADD_TO_PATH_ALL_USERS

; Same body as the template's helper (Function ConditionalAddToRegistry in
; NSIS.template.in): pop a value then a name, write it to the uninstall key unless
; the value is empty. nsis-add-to-path.nsh calls it, so it has to exist here.
Function ConditionalAddToRegistry
  Pop $0
  Pop $1
  StrCmp "$0" "" ConditionalAddToRegistry_EmptyString
    WriteRegStr SHCTX "Software\Microsoft\Windows\CurrentVersion\Uninstall\NetVis" "$1" "$0"
    DetailPrint "Set install registry entry: '$1' to '$0'"
  ConditionalAddToRegistry_EmptyString:
FunctionEnd

Section "Install"
  WriteUninstaller "$INSTDIR\uninst.exe"
  !include "${NETVIS_PKG_DIR}\nsis-add-to-path.nsh"
SectionEnd

Section "Uninstall"
  ; As the template does, immediately before it expands EXTRA_UNINSTALL_COMMANDS.
  ReadRegStr $DO_NOT_ADD_TO_PATH SHCTX \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NetVis" "DoNotAddToPath"
  ReadRegStr $ADD_TO_PATH_ALL_USERS SHCTX \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NetVis" "AddToPathAllUsers"
  !include "${NETVIS_PKG_DIR}\nsis-remove-from-path.nsh"
SectionEnd
